# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

on:
  pull_request:
    paths:
      - "**/*.{ts,md,html,json}"
      - "*.md"
  push:
    paths:
      - "**/*.{ts,md,html,json}"
      - "*.md"

    branches:
      - next
      - main
      - release/*

env:
  NODE_VERSION: '16.x'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint files
        run: yarn lint
